import type { Metadata } from "next";
import "../styles/globals.css";
import { SubtitleProvider } from "@/context/SubtitleContext";
import { AuthProvider } from "@/context/AuthContext";
import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="min-h-screen flex flex-col bg-[#fdfdfd] font-sans text-gray-900 transition-colors">
        <AuthProvider>
          <SubtitleProvider>
            <Navbar />
            <main className="flex-grow">{children}</main>
            <Footer />
          </SubtitleProvider>
        </AuthProvider>
      </body>
    </html>
  );
}

